// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wba.MovieRating.Web.Data;

#nullable disable

namespace Wba.MovieRating.Web.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20251113081353_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("DirectorMovie");

                    b.HasData(
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 2
                        },
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 3
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Ryan",
                            Lastname = "Renolds"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Kim",
                            Lastname = "Basinger"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Pamela",
                            Lastname = "Anderson"
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.ActorMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("Character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 1,
                            Character = "Deadpool",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 2,
                            Character = "Kim",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 3,
                            Character = "Pamela",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 1,
                            Character = "Danny",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 3,
                            Character = "Pamela",
                            MovieId = 3
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Columbia Pictures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marvel"
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Francis F.",
                            Lastname = "Coppola"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Martin",
                            Lastname = "Scorsese"
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            ReleaseDate = new DateTime(2017, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deadpool"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            ReleaseDate = new DateTime(2018, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The suicide squad"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            ReleaseDate = new DateTime(1972, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The godfather"
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.MoviesRating", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("chk_range", "score BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            UserId = 2,
                            Score = 4
                        },
                        new
                        {
                            MovieId = 2,
                            UserId = 2,
                            Score = 5
                        },
                        new
                        {
                            MovieId = 3,
                            UserId = 2,
                            Score = 2
                        },
                        new
                        {
                            MovieId = 1,
                            UserId = 1,
                            Score = 2
                        },
                        new
                        {
                            MovieId = 2,
                            UserId = 1,
                            Score = 3
                        },
                        new
                        {
                            MovieId = 3,
                            UserId = 1,
                            Score = 5
                        },
                        new
                        {
                            MovieId = 1,
                            UserId = 3,
                            Score = 3
                        },
                        new
                        {
                            MovieId = 2,
                            UserId = 3,
                            Score = 2
                        },
                        new
                        {
                            MovieId = 3,
                            UserId = 3,
                            Score = 1
                        });
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Bart",
                            Lastname = "Soete"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Joachim",
                            Lastname = "François"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Dries",
                            Lastname = "Deboosere"
                        });
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("Wba.MovieRating.Core.Entities.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wba.MovieRating.Core.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.ActorMovie", b =>
                {
                    b.HasOne("Wba.MovieRating.Core.Entities.Actor", "Actor")
                        .WithMany("Movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wba.MovieRating.Core.Entities.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Movie", b =>
                {
                    b.HasOne("Wba.MovieRating.Core.Entities.Company", "Company")
                        .WithMany("Movies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.MoviesRating", b =>
                {
                    b.HasOne("Wba.MovieRating.Core.Entities.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wba.MovieRating.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Actor", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Company", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Wba.MovieRating.Core.Entities.Movie", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
